In [1]:
from sklearn import datasets
import matplotlib.pyplot as plt
import numpy as np
import math

iris = datasets.load_iris()
X = iris.data
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [2]:
y = (iris.target ==2).astype(int)
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1]


In [3]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [64]:
print(sigmoid(X))

[[0.9939402  0.97068777 0.80218389 0.549834  ]
 [0.99260846 0.95257413 0.80218389 0.549834  ]
 [0.9909867  0.96083428 0.78583498 0.549834  ]
 [0.9900482  0.95689275 0.81757448 0.549834  ]
 [0.99330715 0.97340301 0.80218389 0.549834  ]
 [0.99550373 0.98015969 0.84553473 0.59868766]
 [0.9900482  0.96770454 0.80218389 0.57444252]
 [0.99330715 0.96770454 0.81757448 0.549834  ]
 [0.98787157 0.94784644 0.80218389 0.549834  ]
 [0.99260846 0.95689275 0.81757448 0.52497919]
 [0.99550373 0.97587298 0.81757448 0.549834  ]
 [0.99183743 0.96770454 0.83201839 0.549834  ]
 [0.99183743 0.95257413 0.80218389 0.52497919]
 [0.98661308 0.95257413 0.75026011 0.52497919]
 [0.99698158 0.98201379 0.76852478 0.549834  ]
 [0.99666519 0.98787157 0.81757448 0.59868766]
 [0.99550373 0.98015969 0.78583498 0.59868766]
 [0.9939402  0.97068777 0.80218389 0.57444252]
 [0.99666519 0.97811873 0.84553473 0.57444252]
 [0.9939402  0.97811873 0.81757448 0.57444252]
 [0.99550373 0.96770454 0.84553473 0.549834  ]
 [0.9939402  

In [106]:
theta = np.ones((X.shape[1],))
iterations = 1500
learningrate = 0.01

print(theta.shape)

m,n = X.shape

for i in range(iterations):
    predictions = sigmoid(np.dot(X, theta))
    errors = predictions -y 
    gradient = np.dot(X.T, errors) / m
    theta =  theta - learningrate * gradient
    
    cost = 1/m * np.sum(-y * np.log(predictions) - (1 - y) * np.log(1 - predictions))
    print(cost)

(4,)
8.144684883132184
7.929856478550024
7.715031351671305
7.500210532995007
7.285395380365502
7.070587683963856
6.855789805532327
6.641004862887931
6.426236974605631
6.211491584814425
5.99677589442429
5.782099433984751
5.567474824855186
5.352918790644966
5.138453500931864
4.92410835530289
4.709922349310288
4.495947206331312
4.282251511574971
4.068926146419672
3.856091390049745
3.6439061230563663
3.432579617080904
3.2223863931715067
3.013684523287189
2.806937446531608
2.602738751732888
2.4018382985747433
2.205166402225585
2.01385063308767
1.8292174552566542
1.652769314276363
1.486128221532472
1.330940698730081
1.1887465792134493
1.0608244349563662
0.9480367090409929
0.8507048515023976
0.7685455611176734
0.7006901956050748
0.645789453690878
0.6021802974120001
0.5680740052396027
0.5417231879249005
0.5215405306263989
0.5061625214901976
0.4944669782276265
0.4855597339988606
0.47874523119599266
0.4734918180588877
0.4693981998995476
0.46616413583462385
0.4635663442869009
0.46143944116760927


0.2899720906106299
0.28988303629435025
0.28979410796215094
0.28970530524770893
0.2896166277862595
0.2895280752145875
0.28943964717101867
0.28935134329541184
0.2892631632291502
0.2891751066151335
0.28908717309776943
0.28899936232296575
0.28891167393812217
0.2888241075921222
0.28873666293532535
0.2886493396195594
0.2885621372981117
0.28847505562572245
0.28838809425857626
0.2883012528542944
0.28821453107192774
0.2881279285719482
0.28804144501624196
0.2879550800681017
0.287868833392219
0.28778270465467715
0.2876966935229434
0.2876107996658621
0.287525022753647
0.28743936245787427
0.28735381845147523
0.28726839040872915
0.28718307800525644
0.28709788091801103
0.28701279882527386
0.2869278314066457
0.28684297834304023
0.28675823931667754
0.2866736140110764
0.28658910211104843
0.28650470330269084
0.28642041727337975
0.2863362437117638
0.2862521823077571
0.286168232752533
0.2860843947385176
0.28600066795938256
0.2859170521100399
0.2858335468866343
0.28575015198653747
0.2856668671083415
0.28558